### ISSUE TITLE
SDMMC1 Conflict with tim3 & FDCAN

### ISSUE THREAD

**Issue by NMSTEC** [riverdi/riverdi-50-stm32u5-lvgl#1]
![image](https://github.com/riverdi/riverdi-50-stm32u5-lvgl/assets/45252464/eb010a5f-b2b9-4f08-9bad-c3e1c79a9499)

**Comment by lukasz-skalski** [comment]
By default, IOC configuration has more peripherals enabled than it is really needed - you need to adjust it to your needs. For example, if you don't need TIM3, you can just disabled it (only TIM15 CH1 is necessary for LCD backlight and TIM2 as a timebase source). If FDCAN1 is enabled, still you can use SDMMC1, but with 4 bits wide bus (pins PB8 and PB9 are used by FDCAN1) - as it is needed for J1 sdcard connector.
