### ISSUE TITLE
Memory leak in example provided

### ISSUE THREAD

**Issue by Sgw32** [riverdi/riverdi-50-stm32u5-lvgl#2]
Hi

I've compiled and flashed the project to Riverdi RVT50HQSNWN00 and turned on memory usage widget in lv_conf.h
The memory usage constantly increases. What to do? 

In my examples it goes to HardFault in a short time. 

Best regards

**Comment by Sgw32** [comment]
Looks like an LVGL issue. 
Switch to release version v8.3.9 of LVGL and problem is solved.

**Comment by lukasz-skalski** [comment]
Thanks for letting know - indeed it could be issue with LVGL. As soon as it will be ready, there is a plan to switch to v9 version.
